
services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
      - ./database/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: docfind-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=db:5432
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: docfind-frontend
    ports:
      - "3000:3000"
    # depends_on:
    #   - backend
    networks:
      - app-network

# create network
networks:
  app-network:
    driver: bridge
