# render.yaml

services:
  # Backend service
  - type: web
    runtime: docker
    name: docfind-backend
    repo: https://github.com/JackPairce/DocFinder.git
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DOCFIND_DB_HOST
        fromDatabase:
          name: docfind-db
          property: host
      - key: DOCFIND_DB_PORT
        fromDatabase:
          name: docfind-db
          property: port
      - key: POSTGRES_USER
        fromDatabase:
          name: docfind-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: docfind-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: docfind-db
          property: database
    plan: free

  # Frontend service
  - type: web
    runtime: docker
    name: docfind-frontend
    repo: https://github.com/JackPairce/DocFinder.git
    rootDir: frontend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DOCFIND_BACKEND_HOST
        fromService:
          name: docfind-backend
          type: web
          property: host
      - key: DOCFIND_BACKEND_PORT
        fromService:
          name: docfind-backend
          type: web
          property: port
    autoDeploy: true
    plan: free

databases:
  # PostgreSQL database
  - name: docfind-db
    plan: free
    databaseName: library
    ipAllowList: [] # Internal connections only
